language: erlang
sudo: false

otp_release:
- 18.2

addons:
  postgresql: "9.4"

before_install:
- psql -c 'create database entice_test;' -U postgres
- wget http://s3.hex.pm/builds/elixir/v1.3.2.zip
- unzip -d elixir v1.3.2.zip

before_script:
- export PATH=`pwd`/elixir/bin:$PATH
- mix local.hex --force
- mix deps.get

script:
- MIX_ENV=test mix ecto.migrate
- MIX_ENV=test mix run priv/repo/seeds.exs
- MIX_ENV=test mix test

notifications:
  irc: irc.rizon.net#gwlpr

deploy:
  provider: heroku
  buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
  strategy: git
  api_key:
    secure: HSDMAqUCQDuOdY9RxFYRb0fMYiEW9RPN63/GO/TJKc9GYjOV3uOD6JRCDhIx+tFIrh+UIbjO6P1cM7sGELYcbGtMrMAIvYP5mC+782qgMK7703q6pYoDRNvDFa161heVZqUehHw2PYHwJGucJqr6O8e9aQ8zKEYfhMPt1E0tBsM=
  app:
    master: entice-web
    develop: entice-web-staging

